steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--platform=linux/amd64', '-f', 'training.Dockerfile', '-t', 'gcr.io/trueorfakenews/training', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/trueorfakenews/training']
