name: Docker Image CI

on:
  push:
    branches: [ master, main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
    - name: Build the Docker image
      run: |
        docker build . --file app.Dockerfile \
          --tag cloudapp gcr.io/trueorfakenews/cloudapp
        docker push cloudapp gcr.io/trueorfakenews/cloudapp

